### ISSUE TITLE
Luaffyn Black face 

### ISSUE THREAD

**Issue by Task7** [ForgottenGlory/Living-Skyrim#115]
**LS Version**
1.6.1

**Describe the bug**
Luaffyn has a black face in Candlehearth Hall. Approaching her or trying to initiate dialogue causes the game to crash.

**To Reproduce**
Approach Luaffyn in Candlehearth Hall

**Expected behavior**
Normal face

**Screenshots**
She's outside in the screenshot but the result is the same. Crashed a second later
![20200413140105_1](https://user-images.githubusercontent.com/63614530/79162077-797a2780-7d91-11ea-8844-d3c03244994a.jpg)

Console Data:
![20200413141348_1](https://user-images.githubusercontent.com/63614530/79162097-8434bc80-7d91-11ea-97b6-c3b2845a6d87.jpg)

**Additional context**
I'm running a base LS install, no additional mods added

**Comment by aryell2linx** [comment]
Adding another NPC with Black Face Bug: Legate Quetin Cipius.
![ScreenShot61](https://user-images.githubusercontent.com/63164998/79219352-c83fc400-7e5a-11ea-9b03-99bcc8ce3ef6.png)
Went to Whiterun for the warning to Balgruuf about Helgen, stumbled on this handsome man.
Vanilla Start.
(see attached screenshot)

**Comment by aryell2linx** [comment]
Old edit: Working an o temporary fix, thank you you know who you are (LD) :)

![ScreenShot64](https://user-images.githubusercontent.com/63164998/79235954-f4683e80-7e74-11ea-8ccb-becb634b62b7.png)
![ScreenShot65](https://user-images.githubusercontent.com/63164998/79235960-f6320200-7e74-11ea-84a1-83d6e019d2bc.png)


Luaffyn crash is also fixed, by fixing the black face bug. So that's good.
[BFBfixes.zip](https://github.com/ForgottenGlory/Living-Skyrim/files/4475839/BFBfixes.zip)
sorry for the zip, but this is the only way I could upload the esp...

Mark this as closed... or wait till I find some more of these.

Side note:
I renamed BFB.esp to BFBfixes.esp

**Comment by ForgottenGlory** [comment]
Fixed for 1.6.2
