### ISSUE TITLE
Reliquary of Myth 

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Living-Skyrim#21]
Reliquary of Myth | https://www.nexusmods.com/skyrimspecialedition/mods/31612?tab=posts&BH=0

**Comment by PKYxReGiGiGaSx** [comment]
I've done a detailed comparison of this mod and the most popular artifact overhaul "Zim's Immersive Artifacts." All I can say is that RoM is consistently better than Zim's in almost every way. It is much more lore-friendly, fun to use, and powerful while being balance.

Phoenix guide is also going to be using Reliquary of Myth over Zim's due to fewer bugs and being more lore-friendly. I would only use the Thane weapons, Nightingale, and Miraak gear modular from Zim and use everything else from RoM as my recommendation.

**Comment by ForgottenGlory** [comment]
Zim's is pretty heavily integrated into LS at the moment both with LOTD and the LS Patches, this likely won't be added until the 2.0.0 rebuild.
