### ISSUE TITLE
Unique Uniques

### ISSUE THREAD

**Issue by Suraru** [ForgottenGlory/Living-Skyrim#64]
Tamrielic Culture 		https://www.nexusmods.com/skyrimspecialedition/mods/11418 
Tail Armors 			https://www.nexusmods.com/skyrimspecialedition/mods/11471 
Warmth 				https://www.nexusmods.com/skyrimspecialedition/mods/2959/? 
Skaal Kid Coat 			https://www.nexusmods.com/skyrimspecialedition/mods/7512/? 
Book Covers 			https://www.nexusmods.com/skyrimspecialedition/mods/901
Unique Uniques 		https://www.nexusmods.com/skyrimspecialedition/mods/3334 

**Why?**
Gives armors more detail, believably, includes items from previous games, and diversifies existing items with unique appereances.

**Comment by ForgottenGlory** [comment]
Kid Coat: Not worth an esp slot
Book Covers: already included in LOTD
Warmth: I'd want the standalone and this mod is definitely not worth 5 esp slots
Tail Armors: Seems like unnecessary bloat and a decent buff to khajiit and argonians. They shouldn't get a buff just because they have tails.

Tamrielic Culture: Maybe in 2.0.0

Unique Uniques: probably fine

**Comment by tr4wzified** [comment]
Unique Uniques is already in LotD.

**Comment by Suraru** [comment]
Tail Armors doesn't buff beast races. It's an armor replacer to add the visual of armor on the tails when they equip vanilla armors.

Didn't know LotD included so many mods!

Warmth and Skaal Kid Coat can be merged with other armor mods to not take up any ESPs (or converted into ESLs)

Recommend title change to Tamrielic Culture, although I was looking at the mod list for Kaziel which includes some better alternatives.
